version: "3.7"
services:
  local-nodejs-db:
    image: mysql:5.7
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "23306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=nodejs-pass